apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: jaeger-inmemory-instance
spec:
  mode: deployment
  image: jaegertracing/jaeger:latest
  ports:
    - name: jaeger-ui
      port: 16686
      protocol: TCP
      targetPort: 0
    - name: otlp-grpc
      port: 4317
      protocol: TCP	
      targetPort: 0
    - name: otlp-http
      port: 4318
      protocol: TCP	
      targetPort: 0
  config:
    service:
      extensions: [jaeger_storage, jaeger_query]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [jaeger_storage_exporter]
    extensions:
      jaeger_query:
        storage:
          traces: memstore
      jaeger_storage:
        backends:
          memstore:
            memory:
              max_traces: 100000
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch:
        timeout: 1s
        send_batch_size: 8192
    exporters:
      jaeger_storage_exporter:
        trace_storage: memstore