apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: {{ .Values.instrumentation.name }}
spec:
  dotnet:
    image: {{ .Values.instrumentation.dotnetImage | quote }}
  exporter:
    endpoint: {{ .Values.instrumentation.exporter.endpoint | quote }}
